name: dispatch
on:
  workflow_dispatch:
      inputs:      
          name:
            description: 'enter name'
            required: true
            default: 'Your name'
            type: string 
          env:
            description: 'set env'
            required: true
            default: 'dev'
            type: choice
            options:
                - dev
                - stg
                - prd

jobs:
    workflow-dispatch-job:
        runs-on: ubuntu-latest
        steps:
          - name: step1
            run: echo 'dispatch test'
          - name: echo inputs
            run: |
              echo "NAME: ${{ inputs.name}}"
              echo "Env: ${{ inputs.env}}"