name: pull-request-workflow
on: 
  pull_request:
    types: [opened]
  schedule:
  - cron:  #default branch, 5분/30분 간격은 drop될 가능성이 있어, 필수 스케줄은 권장하지 않음

jobs:
    pull-request-job:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: |
                echo step1 pull-request
                echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
                echo $NOW 
            - name: step2
              run: |
                echo hello step2
                echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
                echo $NOW 