name: if-condition
on:
  push:
  workflow_dispatch:
    
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: push event
        if: github.event_name == 'push'
        run: echo ${{ github.event_name}}
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: not push event 
        if: github.event_name != 'push'
        run: echo ${{ github.event_name}}
