name: context
on: workflow_dispatch

jobs:
     context:
        runs-on: ubuntu-latest
        steps:
        - name: github context
          run: echo '${{ toJSON(github) }}'
        - name: check github context
          run: |
            echo rep ${{ github.repository}}
            echo workflow ${{ github.workflow }}
