name: environment
on: push

jobs:
    get-env:
        runs-on: ubuntu-latest
        steps:
        - name: cechk env& key
          run: |
            echo ${{ vars.level }}
            echo ${{ secrets.key }}