name: "output-test from another jobs"
on: workflow_dispatch

jobs:
  first_job:
    runs-on: ubuntu-latest
    outputs:  
      share_name: ${{ steps.output1.outputs.name}}
    steps:
      - name: make-output
        id: output1
        run: |
          echo "name=test1" >> "$GITHUB_OUTPUT"
      - name: call-output
        run: |
          echo  ${{ steps.output1.outputs.name }}  

  second_job:
    needs: [first_job]
    runs-on: ubuntu-latest
    steps:
      - name: call-output
        run: |
          echo  ${{ needs.first_job.outputs.share_name }}