name: secrets
on: [push]

jobs:
  get-secret:
    runs-on: ubuntu-latest
    if:  ${{ env.level}} == "repo"
    steps:
      - name: get secrets
        run: |
          echo "checked secret : ${{ secrets.key}} "