name: oidc test
on:
  push:
    branches: ["main"]

env:
  BUCKET: "dada-git-oidc-test"
  AWS_REGION: "ap-northeast-2"
  ROLE_ARN: "arn:aws:iam::365685052515:role/github-action-oidc"

permissions:
  id-token: write
  contents: read

jobs:
  S3FileUpload:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: ${{env.AWS_REGION}}
          role-to-assume: ${{env.ROLE_ARN}}
      - name: copy files
        run: |
          aws s3 sync ./my-app s3://${{ env.BUCKET}}/