name: oidc test
on:
  push:
    branches: ["main"]

env:
  BUCKET: "dada-git-oidc-test"
  AWS_REGION: "ap-northeast-2"
  Role_arn: "arn:aws:iam::365685052515:role/github-action-oidc"

permissions:
  id-token: write # reqeust the JWT
  contents: read  # actinos/checkout

jobs:
  S3FileUpload:
    runs-on: ubuntu-latest
    steps:
      - name: git clone
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentails@v1
        with:
          role-to-assume: 
          role-session-name: ${{env.Role_arn}}
          aws-region: ${{ env.AWS_REGION}}
      - name: copy files
        run: |
          aws s3 sync my-app s3://${{ env.BUCKET}}/